<?php
$menu[]=array(
        'title'=>'Inventaris',
        'link'=>'?view=inventaris',
        'class'=>''
    );
$menu[]=array(
        'title'=>'Pegawai',
        'link'=>'?view=pegawai',
        'class'=>''
    );
    
$menu[]=array(
        'title'=>'Jenis Inventaris',
        'link'=>'?view=jenis-inventaris',
        'class'=>''
    );
$menu[]=array(
        'title'=>'Peminjaman',
        'link'=>'?view=pinjam',
        'class'=>''
    );
?>